configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hdr-parth-agrawal%2Ffirecracker-manager-df3aeb1267c7211ade6c73fe542dc456e8e11ddb59c46e1eca7efff48f3ebaab.yml
openapi_spec_hash: 78dd989316240485639d541df2031eca
config_hash: f66b2769c821cd7898caec141462cfb0
