configured_endpoints: 17
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hdr-parth-agrawal%2Ffirecracker-manager-af56bf453f9c3c822e1b0f5aefebf05a684c3d4593da60312dcfe6e79036fca8.yml
openapi_spec_hash: 0db6c3074227fa7360a3d28bea415593
config_hash: b8ee6bc54f6cee5c39f11be532b7b215
