configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hdr-parth-agrawal%2Ffirecracker-manager-3d3466ac93b61ca643df8bd5a4e2a0b9bc6faf81a048e227abb6defc6c82cffb.yml
openapi_spec_hash: 8c37523ed89c709ce636c56947f96d5c
config_hash: fbac25e826fd4a546ad304b6172abee1
