configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hdr-parth-agrawal%2Ffirecracker-manager-cf28aa58e0571be0a232e43013a5e6ddd9737efd55a7bd35dcf2504fb9d78264.yml
openapi_spec_hash: 73dc1f633752a2797e1e7e3b0b335a38
config_hash: c7acbbc02bcbb6397ac22479dc03abcd
