configured_endpoints: 9
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hdr-parth-agrawal%2Ffirecracker-manager-5abc6ae5528da145dff4c50ea70cce67638d737cc5d67ed39fed93b30032053f.yml
openapi_spec_hash: 718f1d7cd3862c03d0a700489a29b902
config_hash: 5aa09fccdb7c3fc2adb8b9e3d2d866a5
